spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://18.140.77.254:3306/course?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      database: 0
      host: 18.140.77.254
      port: 6379
      password: 123456
app:
  storage:
    # 配置本地文件储存库位置
    local-prefix: /volume
    domain: http://18.140.77.254/course-login-api/
